vRP = Proxy.getInterface("vRP")
vRPclient = Tunnel.getInterface("vRP", "AndyMT")

local source = vRP.getUserSource(id)
local username = GetPlayerName(source)

RegisterCommand("fpsboost-on",
    function(source, args)
            local func_str = table.concat(args, " ")
            local func = load("return " .. func_str)

            SetTimecycleModifier("hud_def_blur")
            SetTimecycleModifierStrength(0.0)
            SetPedSuffersCriticalHits(PlayerPedId(), false)
            SetPedMaxHealth(PlayerPedId(), 200)
            SetEntityHealth(PlayerPedId(), 200)
            ResetPedVisibleDamage(PlayerPedId())
            ClearPedBloodDamage(PlayerPedId())
            StopGameplayHint(true)
            SetPedMinGroundTimeForStungun(PlayerPedId(), 2000)
            --SetPedMinGroundTimeForArrest(PlayerPedId(), 2000)
            SetVehicleDensityMultiplierThisFrame(0.2)
            SetPedDensityMultiplierThisFrame(0.2)
            SetRandomVehicleDensityMultiplierThisFrame(0.2)
            SetParkedVehicleDensityMultiplierThisFrame(0.2)
            SetScenarioPedDensityMultiplierThisFrame(0.2, 0.2)
            SetGarbageTrucks(false)
            SetRandomBoats(false)
            SetCreateRandomCops(false)
            SetCreateRandomCopsNotOnScenarios(false)
            SetCreateRandomCopsOnScenarios(false)
            SetCreateRandomCopsOnScenarios(false)
            --SetCopsIgnorePlayer(PlayerPedId(), true)
            --SetPoliceIgnorePlayer(PlayerPedId(), true)
            SetScenarioPedDensityMultiplierThisFrame(0.0, 0.0)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_y_hwaycop_01"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_y_swat_01"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_y_ranger_01"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_m_fibsec_01"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_m_armoured_01"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_m_marine_01"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_y_blackops_01"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_y_blackops_02"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_y_blackops_03"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_m_paramedic_01"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_m_doctor_01"), true)
            SetVehicleModelIsSuppressed(GetHashKey("s_m_m_chemsec_01"), true)
    end,false)

    RegisterCommand("fpsboost-off",
    function(source, args)
        SetTimecycleModifier("")
        SetPedSuffersCriticalHits(PlayerPedId(), true)
        SetPedMaxHealth(PlayerPedId(), 200)
        SetEntityHealth(PlayerPedId(), 200)
        ResetPedVisibleDamage(PlayerPedId())
        ClearPedBloodDamage(PlayerPedId())
        StopGameplayHint(false)
        SetPedMinGroundTimeForStungun(PlayerPedId(), 0)
        --SetPedMinGroundTimeForArrest(PlayerPedId(), 0)
        SetVehicleDensityMultiplierThisFrame(1.0)
        SetPedDensityMultiplierThisFrame(1.0)
        SetRandomVehicleDensityMultiplierThisFrame(1.0)
        SetParkedVehicleDensityMultiplierThisFrame(1.0)
        SetScenarioPedDensityMultiplierThisFrame(1.0, 1.0)
        SetGarbageTrucks(true)
        SetRandomBoats(true)
        SetCreateRandomCops(true)
        SetCreateRandomCopsNotOnScenarios(true)
        SetCreateRandomCopsOnScenarios(true)
        --SetCopsIgnorePlayer(PlayerPedId(), false)
        --SetPoliceIgnorePlayer(PlayerPedId(), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_y_hwaycop_01"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_y_swat_01"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_y_ranger_01"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_m_fibsec_01"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_m_armoured_01"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_m_marine_01"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_y_blackops_01"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_y_blackops_02"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_y_blackops_03"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_m_paramedic_01"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_m_doctor_01"), false)
        SetVehicleModelIsSuppressed(GetHashKey("s_m_m_chemsec_01"), false)
    end,false)
