Config = Config or {}

Config.Webhook = ''
Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 182
Config.PhoneApplications = {
    ["phone"] = {
        app = "phone",
        color = "#04b543",
        icon = "fa fa-phone-alt",
        tooltipText = "Telefon",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ["whatsapp"] = {
        app = "whatsapp",
        color = "#25d366",
        icon = "fab fa-whatsapp",
        tooltipText = "Whatsapp",
        tooltipPos = "top",
        style = "font-size: 2.8vh";
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ["twitter"] = {
        app = "twitter",
        color = "#1da1f2",
        icon = "fab fa-twitter",
        tooltipText = "Twitter",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ["settings"] = {
        app = "settings",
        color = "#636e72",
        icon = "fa fa-cog",
        tooltipText = "Setari",
        tooltipPos = "top",
        style = "padding-right: .08vh; font-size: 2.3vh";
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ["garage"] = {
        app = "garage",
        color = "#575fcf",
        icon = "fas fa-warehouse",
        tooltipText = "Masinile Tale",
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ["bank"] = {
        app = "bank",
        color = "#9c88ff",
        icon = "fas fa-university",
        tooltipText = "Bank",
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ["advert"] = {
        app = "olx",
        color = "#007872",
        icon = "",
        style = "background-image: url(https://static.olx.ro/static/olxro/naspersclassifieds-regional/olxeu-atlas-web-olxro/static/img/fb/fb-image_redesign.png);",
        tooltipText = "OLX",
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ["gallery"] = {
        app = "gallery",
        color = "#AC1D2C",
        icon = "fas fa-images",
        tooltipText = "Gallery",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    ["camera"] = {
        app = "camera",
        color = "#AC1D2C",
        icon = "fas fa-camera",
        tooltipText = "Camera",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ["police"] = {
        app = "polices",
        color = "#0061e0",
        icon = "fas fa-building",
        tooltipText = "Politie",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ["smurd"] = {
        app = "doctor",
        color = "#ff0000",
        icon = "fas fa-first-aid",
        tooltipText = "Smurd",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
    ["taxi"] = {
        app = "taxi",
        color = "#25d366",
        icon = "fas fa-taxi",
        tooltipText = "Taxi",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ["mechanic"] = {
        app = "mechanic",
        color = "#353b48",
        icon = "fas fa-wrench",
        tooltipText = "Mechanic",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ["traficantarme"] = {
        app = "traficant",
        color = "#000000",
        icon = "fas fa-users",
        tooltipText = "Traficant Arme",
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },	
    ["snake"] = {
        app = "snake",
        color = "#609",
        icon = "fas fa-ghost",
        tooltipText = "Snake Game",
        tooltipPos = "left",
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
    ["mail"] = {
        app = "mail",
        color = "#ff002f",
        icon = "fas fa-envelope",
        tooltipText = "Mail",
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
    },
}

Config.StoreApps = {
    ["territory"] = {
        app = "territory",
        color = "#353b48",
        icon = "fas fa-globe-europe",
        tooltipText = "Territorium",
        tooltipPos = "right",
        style = "";
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
        password = true,
        creator = "QBCore",
        title = "Territory",
    },
}